// Question - 23 , Conditional Test
var car1 = 'Toyota';
var car2 = 'Honda';
var car3 = 'Suzuki';
var car4 = 'Hyundai';
var car5 = 'Audi';
console.log('Is car is Toyota? I predict True');
console.log(car1 == 'Toyota');
console.log('Is car is Toyota? I predict False');
console.log(car1 == 'Honda');
console.log('Is car is Toyota? I predict False');
console.log(car1 == 'Suzuki');
console.log('Is car is Toyota? I predict False');
console.log(car2 == 'Toyota');
console.log('Is car is Toyota? I predict True');
console.log(car2 == 'Honda');
console.log('Is car is Toyota? I predict False');
console.log(car2 == 'Suzuki');
console.log('Is car is Toyota? I predict False');
console.log(car3 == 'Toyota');
console.log('Is car is Toyota? I predict True');
console.log(car3 == 'Suzuki');
console.log('Is car is Toyota? I predict True');
console.log(car4 == 'Hyundai');
console.log('Is car is Toyota? I predict True');
console.log(car5 == 'Audi');
